#!/usr/bin/env bash

source ~/.mobirc

card() {
  open "http://it-com:8080/browse/NEWBLUE-${*}"
}

alias story='card'

mobi() {
  if [[ $# -eq 0 ]]
  then
    cd $MOBI_ROOT
  fi

  if [[ $# -eq 1 ]]
  then
    param=${1}

    if [[ "$param" == "blue" ]]
    then
      cd $MOBI_BLUE_ROOT
    fi

    if [[ "$param" == "jira" ]]
    then
      open 'http://it-com:8080/secure/RapidBoard.jspa?rapidView=39'
    fi

    echo $param | egrep --text --silent "\d{1,}"
    is_a_number=$?

    if [[ $is_a_number -eq 0 ]]
    then
      story $param
    fi
  fi
}

prep-db() {
  ssh bluedb
}

prep-app() {
  ssh blueapp
}

db() {
  mysql -uroot --database=blue
}

ci() {
  open 'http://10.29.2.119:8080/'
}

insert_migrations() {
  ls db/migrate/ | cut -d'_' -f1 | awk '{ printf "(%s),", $0; }' | sed 's/^\(.*\).$/insert into blue.schema_migrations values \1;/g' | pbcopy
}

